before_commands:
    - "composer install --no-dev --prefer-dist"

tools:
    external_code_coverage:
        enabled: true
        timeout: 300
        filter:
            excluded_paths: ["docs", "bin", "tests", "vendor", "data", "features", "examples"]
    php_code_coverage:
        enabled: false
        test_command: phpunit -c phpunit.xml.dist
    php_code_sniffer:
        enabled: false
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "tests/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["docs", "bin", "tests", "vendor", "data", "features", "examples"]
    php_cs_fixer:
        enabled: false
        config:
            level: all
        filter:
            paths: ["src/*", "tests/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["docs", "bin", "tests", "vendor", "data", "features", "examples"]
    php_mess_detector:
        enabled: true
        config:
#            ruleset: phpmd.xml.dist
            design_rules: { eval_expression: false }
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["docs", "bin", "tests", "vendor", "data", "features", "examples"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*"]
    sensiolabs_security_checker: true
