language: php

php:
  - 5.3.3
  - 5.3.27
  - 5.3.28

before_script:
  - composer selfupdate -n
  - composer update --prefer-dist --dev

script:
  - ./vendor/bin/phpunit --strict --coverage-clover ./build/logs/clover.xml
  # - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/
  - php vendor/bin/phpunit --verbose --coverage-clover=coverage.clover
  - wget "https://scrutinizer-ci.com/ocular.phar"
  - php ocular.phar  code-coverage:upload --format=php-clover coverage.clover

after_script:
  - php vendor/bin/coveralls -v
